path: C:/Users/91887/Desktop/Python/yoloV8/dataset  # or wherever your dataset is
train: images/train
val: images/val
test: images/test

nc: 85
names:
  - A10
  - A400M
  - AG600
  - AH64
  - AV8B
  - An124
  - An22
  - An225
  - An72
  - B1
  - B2
  - B21
  - B52
  - Be200
  - C130
  - C17
  - C2
  - C390
  - C5
  - CH47
  - CL415
  - E2
  - E7
  - EF2000
  - EMB314
  - F117
  - F14
  - F15
  - F16
  - F18
  - F22
  - F35
  - F4
  - H6
  - Il76
  - J10
  - J20
  - J35
  - J36
  - J50
  - JAS39
  - JF17
  - JH7
  - KAAN
  - KC135
  - KF21
  - KJ600
  - Ka27
  - Ka52
  - MQ9
  - Mi24
  - Mi26
  - Mi28
  - Mi8
  - Mig29
  - Mig31
  - Mirage2000
  - P3
  - RQ4
  - Rafale
  - SR71
  - Su24
  - Su25
  - Su34
  - Su57
  - TB001
  - TB2
  - Tornado
  - Tu160
  - Tu22M
  - Tu95
  - U2
  - UH60
  - US2
  - V22
  - V280
  - Vulcan
  - WZ10
  - WZ7
  - WZ9
  - XB70
  - Y20
  - YF23
  - Z10
  - Z19
